[pytest]
# Add project root to Python path so tests can import top-level packages
pythonpath = .
addopts = --base-url=https://www.saucedemo.com/ --headed --slowmo=1000
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
markers =
    SMOKE: smoke tests
    REGRESSION: regression tests