[pytest]
# Add project root to Python path so tests can import top-level packages
pythonpath = .
addopts = --base-url=https://www.saucedemo.com/
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
markers =
    FUNCTIONAL: functional tests
    REGRESSION: regression tests
    SMOKE: smoke tests